version: "3.7"

services:
  frontend:
    image: budget-manager_frontend
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    image: backend
    ports:
      - 5001:5001
    environment:
      -  ASPNETCORE_URLS=https://*:5001