version: "3.7"

services:
  frontend:
    image: budget-manager_frontend
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    image: backend
    ports:
      - 5001:5001
    environment:
      -  ASPNETCORE_URLS=https://*:5001
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"